**Тестовое задание**

**Вакансия -  Junior Python Developer**

**Автор - Татьяна Чубукова**


- Необходимо реализовать функцию со следующим интерфейсом:

- def update_matrix(matrix: numpy.ndarray, S: float, Cf: float, unit: str) -> numpy.ndarray
	if unit == ”1X&&yes”:
	   pass
	elif …

- В метод передаются unit [1X&&yes, 1X&&no, 12&&yes, 12&&no, 2X&&yes, 2X&&no], S=float, Cf=float, matrix – двумерная нулевая мат рица 5*5.
- (1X&&yes) - элементы, для которых (номер строки>=номер столбца)&&(номер строки > 0)&&(номер столбца > 0) уменьшаются на S*Cf. Остальные увеличиваются на S.
- (1X&&no) - элементы, для которых (номер строки<номер столбца)||(номер строки==0)||(н омер столбца == 0) уменьшаются на S*Cf. Остальные увеличиваются на S.
- (12&&yes) - элементы, для которых (номер строки!=номер столбца)&&(номер строки > 0)&&(номер столбца > 0) уменьшаются на S*Cf. Остальные увеличиваются на S.
- (12&&no) - элементы, для которых (номер строки==номер столбца)||(номер строки ==0)        (номер столбца == 0) уменьшаются на S*Cf. Остальные увеличиваются на S.
- (2X&&yes) - элементы, для которых (номер строки<=номер столбца)&&(номер строки > 0)&&(номер столбца > 0) уменьшаются на S*Cf. Остальные увеличиваются на S.
- (2X&&no) - элементы, для которых (номер строки>номер столбца)||(номер строки == 0) || (номер столбца == 0) уменьшаются на S*Cf. Остальные увеличиваются на S.

- && - должны выполняться обо услови (*)
- || - должно выполняться любое условие (+)
- Использовать numpy.



**Подключение библиотек**

In [1]:
import pandas as pd
#import matplotlib.pyplot as plt
import numpy as np
#import seaborn as sb
#import math as mt
import timeit


**Создание функции**

In [2]:
def update_matrix(matrix: np.ndarray, S: float, Cf: float, unit: str): 
    C=S*Cf
    if unit == '1X&&yes':
        for i in range(5):
            for j in range(5):
                if (i >= j) & (j>0):
                    
                    matrix[i][j] =(matrix[i][j] - C)
                    
                else:
                    matrix[i][j] = (matrix[i][j] + S)
                   
            
        
    elif unit == '1X&&no':
        
        for i in range(5):
            for j in range(5):
                if (i < j) | (i == 0) | (j == 0):
                
                    matrix[i][j] = (matrix[i][j] - C)
                    
                else:
                    matrix[i][j] = (matrix[i][j] + S)
         
        
    elif unit == '12&&yes':
        
        for i in range(5):
            for j in range(5):
                if (i != j) & (i > 0) & (j > 0):
                
                    matrix[i][j] = (matrix[i][j] - C)
                    
                else:
                    matrix[i][j] = (matrix[i][j] + S)
        print('unit = 12&&yes')
       
    
    elif unit == '12&&no':
        
        for i in range(5):
            for j in range(5):
                if (i == j) | ((i + j) == 0):
                
                    matrix[i][j] = (matrix[i][j] - C)
                    
                else:
                    matrix[i][j] = (matrix[i][j] + S)
        
        
    elif unit == '2X&&yes':
        
        for i in range(5):
            for j in range(5):
                if (i <= j) & (i > 0):
                
                    matrix[i][j] = (matrix[i][j] - C)
                    
                else:
                    matrix[i][j] = (matrix[i][j] + S)
        
        
    elif unit == '2X&&no':
        
        for i in range(5):
            for j in range(5):
                if (i > j) | (i == 0) | (j == 0):
                
                    matrix[i][j] = (matrix[i][j] - C)
                    
                else:
                    matrix[i][j] = (matrix[i][j] + S)
        
    else:
        print('incorrect data')
    return matrix

**Создание двумерной нулевой матрицы**

In [3]:
#двумерная нулевая матрица 5*5
m1=np.zeros((5, 5))
m2=np.zeros((5, 5))
m3=np.zeros((5, 5))
m4=np.zeros((5, 5))
m5=np.zeros((5, 5))
m6=np.zeros((5, 5))
m7=np.zeros((5, 5))
m8=np.zeros((5, 5))

print(m1)
type(m1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


numpy.ndarray

**Тестирование работы функции**

In [4]:
update_matrix (m1,3,4,'1X&&yes') 


array([[  3.,   3.,   3.,   3.,   3.],
       [  3., -12.,   3.,   3.,   3.],
       [  3., -12., -12.,   3.,   3.],
       [  3., -12., -12., -12.,   3.],
       [  3., -12., -12., -12., -12.]])

In [5]:
update_matrix (m2,3,4,'1X&&no')


array([[-12., -12., -12., -12., -12.],
       [-12.,   3., -12., -12., -12.],
       [-12.,   3.,   3., -12., -12.],
       [-12.,   3.,   3.,   3., -12.],
       [-12.,   3.,   3.,   3.,   3.]])

In [6]:
update_matrix (m3,3,4,'12&&yes')

unit = 12&&yes


array([[  3.,   3.,   3.,   3.,   3.],
       [  3.,   3., -12., -12., -12.],
       [  3., -12.,   3., -12., -12.],
       [  3., -12., -12.,   3., -12.],
       [  3., -12., -12., -12.,   3.]])

In [7]:
update_matrix (m4,3,4,'12&&no')

array([[-12.,   3.,   3.,   3.,   3.],
       [  3., -12.,   3.,   3.,   3.],
       [  3.,   3., -12.,   3.,   3.],
       [  3.,   3.,   3., -12.,   3.],
       [  3.,   3.,   3.,   3., -12.]])

In [8]:
update_matrix (m5,3,4,'2X&&yes')

array([[  3.,   3.,   3.,   3.,   3.],
       [  3., -12., -12., -12., -12.],
       [  3.,   3., -12., -12., -12.],
       [  3.,   3.,   3., -12., -12.],
       [  3.,   3.,   3.,   3., -12.]])

In [9]:
update_matrix (m6,3,4,'2X&&no')

array([[-12., -12., -12., -12., -12.],
       [-12.,   3.,   3.,   3.,   3.],
       [-12., -12.,   3.,   3.,   3.],
       [-12., -12., -12.,   3.,   3.],
       [-12., -12., -12., -12.,   3.]])

In [10]:
update_matrix (m7,3,4,'   2X&&no   ')

incorrect data


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
update_matrix (m8,-3,-4,'2X&&no')

array([[-12., -12., -12., -12., -12.],
       [-12.,  -3.,  -3.,  -3.,  -3.],
       [-12., -12.,  -3.,  -3.,  -3.],
       [-12., -12., -12.,  -3.,  -3.],
       [-12., -12., -12., -12.,  -3.]])

**Тест с единичной матрицей**

In [12]:
Z = np.eye(5)
print(Z)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
update_matrix (Z,3,4,'1X&&yes')

array([[  4.,   3.,   3.,   3.,   3.],
       [  3., -11.,   3.,   3.,   3.],
       [  3., -12., -11.,   3.,   3.],
       [  3., -12., -12., -11.,   3.],
       [  3., -12., -12., -12., -11.]])

In [14]:
import time
t = time.perf_counter()
for param in ['1X&&yes', '1X&&no', '12&&yes', '12&&no', '2X&&yes', '2X&&no']:
    update_matrix(m1,3,4,param)
print(time.perf_counter()-t)


unit = 12&&yes
0.0064821999999997715


In [15]:
import time
t = time.perf_counter()
for param in ['1X&&yes', '1X&&no', '12&&yes', '12&&no', '2X&&yes', '2X&&no']:
    update_matrix(m1,3,4,param)
print(time.perf_counter()-t)

unit = 12&&yes
0.0011545999999995615
